name: ao3pub
networks:
  ao3pub-svcs:
services:
  back:
    build: ../back
    develop:
      watch:
        - action: rebuild
          path: ../back
    networks:
      - ao3pub-svcs
  front:
    build:
      context: ../front
      dockerfile: Dockerfile.testbed
    command: npm run dev -- --host
    develop:
      watch:
        - action: sync
          ignore:
            - node_modules
          path: ../front
          target: /app
        - action: rebuild
          path: ../front/package.json
    networks:
      - ao3pub-svcs
    ports:
      - "9090:9090"
  router:
    image: nginx:1.27-bookworm
    networks:
      - ao3pub-svcs
    ports:
      - "8080:80"
    volumes:
      - ./ao3pub-router-nginx-config.conf:/etc/nginx/nginx.conf:ro
